stages:

  data_acquisition:
    cmd: >
      python src/acquire_data.py
      --raw_data data/raw/Hospital_General_Info.xlsx
      --output_data data/processed/data_clean.parquet
    
    deps:
      - src/acquire_data.py
      - data/raw/Hospital_General_Info.xlsx

    outs:
      - data/processed/data_clean.parquet


  preprocess_data:
    cmd: >
      python src/preprocess_data.py
      --clean_data data/processed/data_clean.parquet
      --proc_data data/processed/data_final.parquet
    
    deps:
      - src/preprocess_data.py
      - data/processed/data_clean.parquet

    outs:
      - data/processed/data_final.parquet
  

  eda_notebook:
    cmd: >
      mkdir -p reports && python -m papermill
      notebooks/eda_notebook.ipynb
      reports/eda_report.ipynb
    deps:
      - notebooks/eda_notebook.ipynb
      - data/processed/data_final.parquet
      - data/raw/Hospital_General_Info.xlsx
    outs:
      - reports/eda_report.ipynb:
          persist: true


  split_data:
    cmd: >
      python src/split_data.py
      --get_data data/processed/data_final.parquet
      --output_train data/processed/train_data.parquet
      --output_test data/processed/test_data.parquet
    
    deps:
      - src/split_data.py
      - data/processed/data_final.parquet

    outs:
      - data/processed/train_data.parquet
      - data/processed/test_data.parquet


  train_rf_model:
    cmd: >
      python src/models.py
      --select_model rf
      --train_data data/processed/train_data.parquet
      --test_data data/processed/test_data.parquet
      --preds preds/rf_preds.parquet
      --models models/rfr.joblib
      --random_seed 75
    
    deps:
      - src/models.py
      - data/processed/train_data.parquet
      - data/processed/test_data.parquet
    
    outs:
      - models/rfr.joblib
      - preds/rf_preds.parquet


  train_xgb_model:
    cmd: >
      python src/models.py
      --select_model xgb
      --train_data data/processed/train_data.parquet
      --test_data data/processed/test_data.parquet
      --preds preds/xgb_preds.parquet
      --models models/xgb.joblib
      --random_seed 75
    
    deps:
      - src/models.py
      - data/processed/train_data.parquet
      - data/processed/test_data.parquet
    
    outs:
      - models/xgb.joblib
      - preds/xgb_preds.parquet

  evaluate_model:
    cmd: >
      python src/evaluate.py
      --rf_preds preds/rf_preds.parquet
      --xgb_preds preds/xgb_preds.parquet
      --metrics_out metrics/metrics_report.json

    deps:
      - src/evaluate.py
      - preds/rf_preds.parquet
      - preds/xgb_preds.parquet

    outs:
      - metrics/metrics_report.json


  #stack_models:
  #  cmd: >
  #    python src/stack_models.py
  #    --get_rf_model models/rfr.joblib
  #    --get_xgb_model models/xgb.joblib

#    deps:
#      - models/rfr.joblib
#      - models/xgb.joblib

  



