stages:

  data_acquisition:
    cmd: >
      python src/acquire_data.py
      --raw_data data/raw/Hospital_General_Info.xlsx
      --output_data data/processed/data_clean.parquet
    
    deps:
      - src/acquire_data.py
      - data/raw/Hospital_General_Info.xlsx

    outs:
      - data/processed/data_clean.parquet


  preprocess_data:
    cmd: >
      python src/preprocess_data.py
      --clean_data data/processed/data_clean.parquet
      --proc_data data/processed/data_final.parquet
    
    deps:
      - src/preprocess_data.py
      - data/processed/data_clean.parquet

    outs:
      - data/processed/data_final.parquet
  

  eda_notebook:
    cmd: >
      mkdir -p reports && python -m papermill
      notebooks/eda_notebook.ipynb
      reports/eda_report.ipynb
    deps:
      - notebooks/eda_notebook.ipynb
      - data/processed/data_final.parquet
      - data/raw/Hospital_General_Info.xlsx
    outs:
      - reports/eda_report.ipynb:
          persist: true


  split_data:
    cmd: >
      python src/split_data.py
      --get_data data/processed/data_final.parquet
      --output_train data/processed/train_data.parquet
      --output_test data/processed/test_data.parquet
    
    deps:
      - src/split_data.py
      - data/processed/data_final.parquet

    outs:
      - data/processed/train_data.parquet
      - data/processed/test_data.parquet

