stages:
  data_acquisition:
    cmd: >
      python src/acquire_data.py
      --raw_data data/raw/Hospital_General_Info.xlsx
      --output_data data/processed/data_clean.parquet
    
    deps:
      - src/acquire_data.py
      - data/raw/Hospital_General_Info.xlsx

    outs:
      - data/processed/data_clean.parquet

  preprocess_data:
    cmd: >
      python src/preprocess_data.py
      --clean_data data/processed/data_clean.parquet
      --proc_data data/processed/data_final.parquet
    
    deps:
      - src/preprocess_data.py
      - data/processed/data_clean.parquet

    outs:
      - data/processed/data_final.parquet

